### ISSUE TITLE
Could you please provide an example for general workflow?

### ISSUE THREAD

**Issue by jacktang** [manu-mannattil/nolitsa#7]
Hello there!

Thanks for the `General Workflow` and `tips` in examples dir, and could you please provide an example for general workflow?

**Comment by jacktang** [comment]
Hello @manu-mannattil , thanks for you kindly suggestions! 
I meant an example involved the whole worflow.  In the example there is an assumption that the dataset need to be applied such step, but not answered the question: why need this step?/what's problem if this step is not involved? As you suggested, maybe some paper or book will answer my question :), could you please recommend some reading materials? Thank you!

**Comment by manu-mannattil** [comment]
I'm not sure I fully understand your question.  Nonlinear time series analysis was historically developed to ascertain the presence of low-dimensional chaos and/or determinism in experimental data.  However, the exact methods you would use would depend on your goals and the data you want to analyze.  A good introduction to the techniques involved is the book by Kantz and Schreiber ["Nonlinear Time Series Analysis" (Cambridge, 2003)] and references in that book.

The "general workflow" I outlined in the examples section is just a guideline, based on my experiences when I wrote two papers that made use of these techniques.  There is no requirement that you follow it.

Perhaps I would be able to better understand your question if you can tell me why you want to use nonlinear time series analysis.  Is there a specific data set you want to analyze?  Do you suspect the presence of chaos/determinism?  What kind of indicators of determinism are you interested it?
